### ISSUE TITLE
Revise Formulsammlung / Calculations sheet

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#103]
Check Illias's email, revise the sheet, edit, and finally send to Illias

**Comment by hillias** [comment]
The fomula sheet we use for the lectures (EK1, EK2, EK3?, eventually BS1 and BS2) should reflect the equations/calculations/system components in HIVE. To do so, please update or suggest any equations which are not yet on the formula sheet by reporting/discussing them with me.

**Comment by amraladdin** [comment]
@hillias where can I find the latest version of the formula sheet?

**Comment by christophwaibel** [comment]
> @hillias where can I find the latest version of the formula sheet?

Hey @amraladdin ,
see here: https://github.com/architecture-building-systems/hive/issues/123#issuecomment-577127357

**Comment by hillias** [comment]
@amraladdin @christophwaibel Regarding Calculation sheet, the latest release is usually on moodle, e.g.: https://moodle-app2.let.ethz.ch/course/view.php?id=11111

In the future, we will also want to provide a copy of the calculation sheet on our A/S consultation platform hosted by Chirag (https://moodle-app2.let.ethz.ch/course/view.php?id=11917)

And we also might want to provide an english version, e.g. for our MBS students (second priority, first focus on german version)

In case you want to revise/update/expand the sheet, feel free to make suggestions directly in the word file and keep it somewhere, were we can track updates/versions (github?). The sheet has been revised a few times in the last couple years and, despite the fact it considerably improved, it is not yet, where it should be. Ideas for further improvement:

- Critically review the equations and variables whether they make sense for early design stage calculations (HIVE and EK1-3 lectures). They should be as simple as possible yet correctly reflect dependencies between design choices and performance (I think an accuracy of 20-30% is acceptable).
- Nomenclature/Use of symbols should be consistent throughout the sheet (and HIVE).
- Add typical values for selected parameters (e.g. typical efficiencies, COP's, ... similar to the drop-down? menus planned for HIVE).
- Instead of equations, rule of thumbs might be added where appropriate.
- Add comments to each topic/equation which show origin, simplifications and/or references in case someone wants to get further information or look up, how the equation was derived. Most of the current equations are from the lecture slides, sometimes with missing references :-(, or from SIA 2024/380.

Ultimately, Arno will need to update his lecture slides to match the equation sheet and input/ouputs from HIVE. I'm assuming, he would want to do this in the summer break. I.e. by August he would need a final version of the equation sheet.
 

[EK1_Formelsammlung_HS19.docx](https://github.com/architecture-building-systems/hive/files/4134174/EK1_Formelsammlung_HS19.docx)

**Comment by christophwaibel** [comment]
@amraladdin @hillias fyi: I unassigned myself from this issue to focus on coding Hive

**Comment by daren-thomas** [comment]
this is done.
