### ISSUE TITLE
EPW-reader

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#114]
Component to open a weather file and extract relevant information in readable format for all the simulation components. Ladybug has it already. But I guess we need our own one?

**Comment by daren-thomas** [comment]
@christophwaibel note: [the CEA has a module](https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/master/cea/utilities/epwreader.py) that we could use as a start, but we should use the `csv` module instead of `pandas` to read the file, as IronPython in GH doesn't ship with pandas.

**Comment by christophwaibel** [comment]
perfect, I'll look into that

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/pull/115
