### ISSUE TITLE
GhVisualizer sankey goes havoc with negative elec demand

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#409]
![image](https://user-images.githubusercontent.com/21927657/93029672-01a07980-f61d-11ea-8ea9-f4a1703d28c4.png)

this can happen if we have overproduction (pv elec)

**Comment by daren-thomas** [comment]
how to display negative values in a sankey diagram???

@christophwaibel idea: excess energy fed to grid (question @amraladdin color?)

@christophwaibel can you give me an example `.gh` file? (or a quick hint how to create one myself)

**Comment by ChrisZenhub** [comment]
hi @daren-thomas :

could you do following changes to the sankey diagram:

- add arrow in "Outputs" for "Surplus Electricity" - color: #CCFF99, RGB 204,255,153
- add arrow in "Outputs" for "Active Cooling" - color: #CCFFFF, RGB 204,255,255
- deactivate the arrow in Outputs "Primary Transfer Losses" for now, because I don't know what to plug in here

**Comment by ChrisZenhub** [comment]
@daren-thomas This issue needs to be fixed by me, issue #423. you can close and ignore this issue here
