### ISSUE TITLE
Make Model-View-ViewModel for GhVisualizer consistent

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#410]
Most data is entered in `ResultsPlotter`, which is good. But some needs to be entered in the `Plots` namespace (KPIs, monthly demand data...)

Can we make this consistent, so I can find it more easily? I.e. all in `ResultsPlotter`

**Comment by daren-thomas** [comment]
I've updated the DemandMonthly plots to use the `ResultsPlotting` class directly.

I won't add the KPI stuff to `ResultsPlotting` because the whole _point_ is that the data adaptor is selected based on the current KPI. It already uses the `ResultsPlotting` class as the basis for the data. So I think this is how it should be.

**Comment by christophwaibel** [comment]
> hat the data adaptor is selected based on the current KPI.

I can't quite follow what you're saying. But the KPIs are derived values anyway and don't need to be *directly* provided by the Results class, right? So then it's fine to me.

My point was just to have all the data that I need to feed from `Results` into the plots in one place, and that I don't need to jump between classes

**Comment by daren-thomas** [comment]
Yes. They're derived. And yes. All the data fed into the plots now come from `ResultsPlotting`.
