### ISSUE TITLE
PV model add f_cover and PR

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#520]
add parameter for coverage (e.g. coloured PV) and add performance ratio (set to by default 0.85) to account for system losses (cabling, etc.)

But we keep the nominal operating cell temperature model

https://miro.com/app/board/o9J_leSAuA0=/

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/62f38ff3-85ca-4e78-8f0b-6ab0c8992b98)

Changes to Energy Systems Hizard:
- move fields for spec emissions and embodied emissions to the right
- make text fields for spec emissions and embodied emissions the same width as spec cost and capital cost text fields
- change labels from `Specific Embodied Emissions` to `Spec. Emb. Emissions` to make it fit 
- remove the text label `(%)` next to `Module Efficiency`, because it is not in percentage, it is fraction
- add text labels `Performance ratio` and `Surface transmittance` beneath `Module Efficiency` and add two corresponding text fields (only numeric input, max 1.0, min 0.01, default for performance ratio 0.85, default for surface transmittance to 1.0)

**Comment by ChrisZenhub** [comment]
**public void SetInputComputeOutput( ...)**
 for (int t = 0; t < horizon; t++)
            {
                ...
                double eta = this.RefEfficiencyElectric * (1 - this.Beta * (tempPV - refTemp)) * this.PR * this.f_cover;

**Comment by ChrisZenhub** [comment]
**public void SetInputComputeOutputSimple( ...)**
            for (int t = 0; t < horizon; t++)
            {
                electricityGenerated[t] = meanIrradiance[t] \* this.SurfaceArea \* this.RefEfficiencyElectric \* this.PR / 1000.0 ** \* this.f_cover; **
