### ISSUE TITLE
Add electrical load or efficiency of lighting and utilities in Building component

### ISSUE THREAD

**Issue by maxenceryan** [architecture-building-systems/hive#566]
## Problem

When calculating electrical demands in the sia380 component, only heat gains are provided used since there is no information about efficiencies of lighting in the building/room or utilities. This underestimates electricity demand

## Proposal

- electrical load of lighting. For instance Light Heat gain = ... W/m2 and Lighting Electrical = W/m2
- efficiency. Lighting Efficiency = ... %
  -  For demand calcs, we can then determine electrical load with efficiency and heat gain.
- In Building component, choose from dropdwon list? LED, Fluorescent, incandescent, torches...
- Or based on lux? Probably too much...

**Comment by maxenceryan** [comment]
per discussion:

SIA 380 seems to provide some values for equipment loads / heat fractions (Reduktionsfaktor) as seen in the tables here. There are also other values for occupancy.

![image.png](https://images.zenhubusercontent.com/5d38d5318f4bde000110956b/1abda5a1-1a55-49c0-a0c9-275e1cf40350)

This however can come into conflict with SIA 2024 perhaps?

Linus' SIA 380 uses the values from SIA 380 rather than SIA 2024 (which is what hive uses atm)

For instance: https://github.com/architecture-building-systems/sia_380-1-full_version/blob/master/data_prep.py#L52

One other point seen in the table is the mismatch of building types compared to SIA 2024. Why is this the case?

**Comment by ChrisZenhub** [comment]
According to SIA 2024 (2015), building category I (SIA 380): 
- room type "2.1 Hotel":
  - 12 kWh/m2a E_A
  - 3 kWh/m2a E_{L+L,AC}
- room type "1.1 MFH":
  - 14 kWh/m2a E_A
  - 4 kWh/m2a E_{L+L,AC}

SIA 2024 furthermore offers a breakdown between "Wärmeeintragsleistung der Raumbeleuchtung/Geräte" and "Elektrische Leistung der Raumbeleuchtung/Geräte", but they are the same.

According to SIA 380/1: 2009, building category I (table 12 and 13):
- 28 kWh/m2a annual electricity demand
- 0.7 reduction factor for internal heat gains
- results in 19.6 kWh/m2a heat gains from electric appliances

I have no idea why there is this mismatch between the norms. There is something that we must be missing. But for now I suggest we simply use the reduction factors from SIA 380/1 and apply them to the loads of SIA 2024. The loads from sia2024 seem alright, e.g., look at "3.1 Einzel- Gruppenbüro", 7; 3; 15 W/m2 for appliances and 15.9; 11.6; 15.9 W/m2 for lighting (Standard; Ideal; Bestand). Those numbers seem alright. 

Either way, reduction factor, as well as equipment and lighting electricity demand will be/are parameters that can be overwritten in the Hizard.

The building categories (I, II, III, IV, V, ...) are referenced in SIA 2024 and SIA 380/1, so we match the reduction factors to each sia2024 room accordingly.

** TO DO **
- add number field in building hizard for reduction factor (or call it "heat gain factor") for equipment and lighting respectively
- rename fields "Equipment heat" and "Lighting Heat" in the hizard to "Equipment power" and "Lighting power" or something, coz it's not just heat anymore
- pass on the correct loads into the json schedules as part of Hive.building that goes out of the hizard, such that the demand calculation will work with the correct loads

**Comment by ChrisZenhub** [comment]
alright, @maxenceryan,  after discussions with @hillias , we've decided to stick to the sia 2024 values and, to keep it simple, ignore the reduction factor from sia380. Therefore, this issue will be closed

background: reduction factor describes any heat that would leave the thermal zone:

"Dieser Reduktionsfaktor berücksichtigt den innerhalb der thermischen Gebäudehülle wirksamen Anteil der Abwärme von Elektroanlagen. Dieser ist gleich dem internen Wärmeeintrag Elektrizität O;,ei· Nicht oder nicht voll wirksam ist z.B. der Elektrizitätsbedarf für Abluft- und Fortluftventilato- ren, für die Wassererwärmung in Wasch- und Abwaschmaschinen und für Wäschetrockner sowie für die Beleuchtung in unbeheizten Gebäudeteilen."

Therefore, in residential buildings the reduction factor causes more heat loss (0.7) due to dishwasher and laundry etc, whereas in an office (e.g., Verwaltung) that value is 0.9 because there is not much laundry.
