### ISSUE TITLE
Create Troubleshooting Wiki Page

### ISSUE THREAD

**Issue by nkobylinska** [architecture-building-systems/hive#597]
## Lack of compatibility with Rhino 6 old versions (6.13)

The version on my system was 6.13 and after installing Hive I got an error "GH library components were developed against a newer minor version of Grasshopper SDK". Fixed with upgrade to 6.34 version, but just fyi.

## Prevent re running of hive when looking at prarams

#603

**Comment by maxenceryan** [comment]
Thanks for the feedback :) 

@christophwaibel  either we update the readme OR installer *could* build things (rather than just copy files) via honey-badger based on the SDK of a user's machine.... but feels a bit overkill. and if we were using older SDK on a newer rhino version/SDK it should still work (see [the honey badger readme](https://github.com/architecture-building-systems/honey-badger)).

**Comment by ChrisZenhub** [comment]
to do: add information / troubleshooting on the WiKi

**Comment by ChrisZenhub** [comment]
also mention about #603

**Comment by maxenceryan** [comment]
@christophwaibel wasnt sure how to make a PR for the wiki, so please check recent changes there. [Troubleshooting page](https://github.com/architecture-building-systems/hive/wiki/Troubleshooting)
