### ISSUE TITLE
Shading Mask not correctly  displayed? "BUG" 

### ISSUE THREAD

**Issue by Lementi** [architecture-building-systems/hive#602]
I wonder why the shading mask shows that there is very little solar potential for building 2 (see file). This can't be right, though I couldn't find a reason why. I've tested the same settings for other buildings, which worked well. 

[Hive_TestingJune21_E3_Schönfelder.zip](https://github.com/architecture-building-systems/hive/files/6704248/Hive_TestingJune21_E3_Schonfelder.zip)

![shading mask weird II](https://user-images.githubusercontent.com/46969062/123148280-51d82200-d460-11eb-9c37-289c35fdf1d0.PNG)
![shading mask weird](https://user-images.githubusercontent.com/46969062/123148285-53094f00-d460-11eb-9871-1e6f3c0e3484.PNG)

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/096ad8ee-1b04-48e8-ad35-532c163106ba)

That is because the Sensor Point is inside a city context building (see screenshot).

However, something that should be kept in mind is that, by default in this GH template, it uses your building centroid projected to the ground floor. So If you are designing a U-shape building, if you are unlucky, the centroid might really lie in a shaded place.

Quick fix for now in that situation: You'd have to manually pick out the sensor point of the GHSkydome component.

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/f35609d3-86de-4d56-8837-49afd1ec7f42)

this is the sensor point that defines the location of the shading mask
