### ISSUE TITLE
Higher volumetric air flow rate of ventilation produces heating demand in summer

### ISSUE THREAD

**Issue by lillaa** [architecture-building-systems/hive#617]
Hi

I am not sure whether this is a bug. 

According to the _exercise 1 - Refurbisment_ I was playing around with the volumetric air flow rate. Obviously, it produces a higher heating demand in winter but it is very counter intuitive that it generates heating demand in July and August. The printsreens you can find below.

 **Settings:"Bestand" Default** 
<img width="539" alt="Bildschirmfoto_Hive_best_defaultsettings" src="https://user-images.githubusercontent.com/65337382/123628915-ea312680-d813-11eb-868e-f0a017d63c3a.png">

**Settings: "Bestand", ventilation rate 3.0**
<img width="464" alt="Bildschirmfoto_Hive_best_vent  3 0" src="https://user-images.githubusercontent.com/65337382/123628929-ee5d4400-d813-11eb-81d7-6686721cec26.png">

**Comment by christophwaibel** [comment]
@lillaa finally looking into it... :) 
In june, the monthly average temperature is 16 deg C, while the set point is at 20 deg C. That's why in "Bestand" (engl: existing building) with bad insulation values, and with higher ventilation rates, (and low solar gains...?), we have heating demand in June. Increasing ventilation rate consequently also increases heating load, because it calculates with 16 deg C

![image](https://user-images.githubusercontent.com/21927657/213750634-fe85b67d-78ed-4a70-9527-18a1d81890dd.png)

Thanks to this issue I have found a bug that Hive wouldn't work anymore with "Bestand" in the current version 1.17, because it tried to cast a string...
