### ISSUE TITLE
re-design of the Energy systems Hizard

### ISSUE THREAD

**Issue by TianjiaoYang** [architecture-building-systems/hive#627]
![image](https://user-images.githubusercontent.com/55989746/123650201-a695e700-d82a-11eb-8013-714b2ac5150a.png)
Hi,

I accidentally added one more system, and I did not find a way to delete the extra entry. Although I was able to assign 0 square meter to the system, which could be an equivalent to deleting, it still would be nice to be able to delete.

Keyword: FEATURE

**Comment by christophwaibel** [comment]
Hi @TianjiaoYang ,
thanks. Yes, this should be possible, but it is a little bit buggy. You can use the "del" key on your keyboard to remove entries. On a mac, that would be Fn+backspace (I believe)

**Comment by ChrisZenhub** [comment]
changing this issue to improving user experience of the EnergySystems hizard:
- unintuitive to add a new row
- unintuitive to delete a row

suggested changes as per discussion:
- swap columns "source" and "conversion", because "conversion" is what we choose
- add a "plus" sign (or similar) for adding a new row. "plus" goes next to column header "conversion"
- add a "minus" sign at the left to the row

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/d91eb2f5-d993-4d00-b9fb-07634ae82c8c)

**Comment by ChrisZenhub** [comment]
Design proposal

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/0b5f1ef5-177e-49f8-8400-6e904b4145e5)

**Comment by ChrisZenhub** [comment]
renamed the title of the issue
