### ISSUE TITLE
Capacity text label in PV Systems hizard does not show any value

### ISSUE THREAD

**Issue by TianjiaoYang** [architecture-building-systems/hive#628]
![image](https://user-images.githubusercontent.com/55989746/123650712-202dd500-d82b-11eb-8bab-823c51b4b4e4.png)

Hi,

it seems I have a different interface for defining the PV systems than the one in the video tutorial, but the capacity part is always disabled. I have no idea what the capacity of my PV system is and I'm not able to manually input a value either, although the PV simulation did run and gave me a result. 

Personally, I think it would be nice if I could manually give a capacity value in **kW/m2**, or the dialog box gives a default/typical value based on the Module Type that I selected. 

Keyword: ENHANCEMENT

**Comment by christophwaibel** [comment]
Hi @TianjiaoYang ,
thanks for your input! So in Hive, you would design your PV with geometry. The capacity is therefore depending on the surface area that you modelled and assigned as PV, as well as on the PV technology (it's efficiency).

I will change this issue to "Bug", because the Capacity field should show the kW_peak

**Comment by ChrisZenhub** [comment]
@philipschulz is this being addressed in PR #666?

**Comment by philipschulz** [comment]
No, currently working on displaying these calculated values (also embodied emissions and capex)

**Comment by philipschulz** [comment]
Closed in pr #666
