### ISSUE TITLE
Results comparison between v1.10.2 and v1.12

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#647]
Compare the load calculation results between [v1.12](https://github.com/architecture-building-systems/hive/releases/tag/v1.12) and [v1.10.2](https://github.com/architecture-building-systems/hive/releases/tag/v1.10.2) for 2-3 different weather files, using the template file from [Module M04 exercise](https://moodle-app2.let.ethz.ch/course/view.php?id=15054) of the online Hive course.

Pay attention to 
- the checkboxes in the building hizard for adaptive comfort in the SIA tab
- the checkbox in the building hizard for natural ventilation in the ventilation tab, 
- and the construction type (for thermal mass) parameter in the SIA tab

and document what impact that has on loads.

**Comment by justinfmccarty** [comment]
[results_comparison_summary.pdf](https://github.com/architecture-building-systems/hive/files/6982569/results_comparison_summary.pdf)
See attached file for the link to the data and plots of the results of my comparison. There is difference between the two versions. Used three climates. Magnitude of changes are difference but between each type of load there appears to be consistent changes.

In newer version used the adaptive comfort checkbox, did not turn on the natural ventilation checkbox (can rerun if this was wrong), and used medium type construction type.

**Comment by christophwaibel** [comment]
many thanks @justinfmccarty !

some quite extreme differences between the versions. @maxenceryan any idea on how this might be caused?

**Comment by maxenceryan** [comment]
thanks for doing this @justinfmccarty !

the results do look quite different, especially on a percentage level. Also important to note that the highest percentage difference occur when there is actually a small load (like tail ends of cooling loads are small in kWh but vastly different in %).

In terms of changes, the main ones in sia380 component are (for monthly calc):
- variable tau instead of fixed (could be the cuplrit but i have to look more closely)
- natural ventilation (but this was turned off)
- u-values and Q_T by component (i doubt this is the reason, unless gh file has custom values in hizard)
- reorganisation of code for hourly (so maybe some error here, but I doubt it)
- refactorings here and there

I have to see more closely, especially with tau

but for me **the red flag is the changing electricity load** as this should have stayed the same...

will update laters

**Comment by maxenceryan** [comment]
per discussion

- #651 created to better see if the variable tau is the reason for this disparity
- changing electricity might be due to electricity required by heating / cooling systems
- would be good to also compare kwh values not just %

**Comment by justinfmccarty** [comment]
> 
> 
> per discussion
> 
>     * [Hizard - Create a "default" construction type that takes tau from SIA 2024 (non-variable) #651](https://github.com/architecture-building-systems/hive/issues/651) created to better see if the variable tau is the reason for this disparity
> 
>     * changing electricity might be due to electricity required by heating / cooling systems
> 
>     * would be good to also compare kwh values not just %

I can make some kWh plots and comparisons when get back to the office Wednesday. The data is available here though https://nextcloud.ethz.ch/s/9ZBzWatnDxyF3oe, specifically "monthly_results_comparison_all.xlsx"

**Comment by christophwaibel** [comment]
some more comparisons between v1.10.2 and upcoming v1.13 in recent PR discussion #653
