### ISSUE TITLE
Annual Demand | CDD and HDD

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#68]
(from WP_Components.xlsx)

Create a "Cooling Degree Days" and "Heating Degree Days" component for Demand assessment and Simulation.

Questions:

- what is the model to use?
- where can I find documentation?
- what are the test inputs / outputs for the components?

**Comment by amraladdin** [comment]
The aim of this component is to calculate the demand using a simplified Heating Degree Days and Cooling Degree Days method.
Since the HDD and CDD calculation sometimes differs from one country to another, a universal HDD or CDD sometimes produces non-realistic results.
For that, together with Stefan Caranovic, we made an excel sheet to calculate the HDD and CDD according to national standards in Germany and Switzerland. You can find the file attached here:

[HDD_CDD.xlsx](https://github.com/architecture-building-systems/hive/files/3436056/HDD_CDD.xlsx)

**Comment by christophwaibel** [comment]
I believe co

> The aim of this component is to calculate the demand using a simplified Heating Degree Days and Cooling Degree Days method.
> Since the HDD and CDD calculation sometimes differs from one country to another, a universal HDD or CDD sometimes produces non-realistic results.
> For that, together with Stefan Caranovic, we made an excel sheet to calculate the HDD and CDD according to national standards in Germany and Switzerland. You can find the file attached here:
> 
> [HDD_CDD.xlsx](https://github.com/architecture-building-systems/hive/files/3436056/HDD_CDD.xlsx)

I believe column E in that excel is wrong. Shouldn't it be `=IF(A#>20,(A#-20),0)`?

**Comment by daren-thomas** [comment]
we're computing monthly demand and don't need this.
