### ISSUE TITLE
Migrate Hive.Core.sia380

### ISSUE THREAD

**Issue by maxenceryan** [architecture-building-systems/hive#688]

**Comment by christophwaibel** [comment]
related to the epw distributor only writing an epw object by default ( https://github.com/architecture-building-systems/hive/pull/692#issuecomment-996655800 ), can this new sia380 read in an epw object by default? that will be more efficient, computationally, instead of having lots of DA.GetDataLists of weather data.

However, from a user perspective, it would be nice, if the sia380 component could still read in such DataLists, but only does it if no epw-object is provided. Because a regular user might not want to be working with an epw-hive-object

**Comment by maxenceryan** [comment]
in the end i ran out of time modifying the inputs such that they read objects... first had to make sure the results were 1;1 with the python component, which took some time. So i suggest creating a new issue to refactor the C# sia380 component to take advantage of other Hive.IO classes as well
