### ISSUE TITLE
replace electricityMerger ghpython component in Core

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#701]
**Describe the bug**
There are custom ghpython components for merging grid electricity in the main template. They use `import Hive.IO.EnergySystems`, which will not work anymore once we remove the `epw_reader.py` component from honeybadger (#692 ). In that python script, we load in dependencies that make this import work. But once we create a proper Hive.IO component for merging electricity, we won't need these dependencies anymore.

```
clr.AddReferenceToFileAndPath(os.path.join(path, "Libraries\Hive", "Hive.IO.gha"))
import Hive.IO.EnergySystems as ensys
```

**To Reproduce**
remove `Hive.Core.epw_reader.ghpy` from the grasshopper components libraries folder and the main hive template will stop working properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/21927657/146926556-4bd6b0db-3010-4f0a-8157-9b4fe0b90ffb.png)

**Software**
 - build from #692 

**Additional context**
[related comment from earlier PR](https://github.com/architecture-building-systems/hive/pull/692#issuecomment-998718181)

**Comment by ChrisZenhub** [comment]
To Do:
- modify the grasshopper component `\Hive.IO\GhMergers\`GhPurchasedElectricity.cs`
- instead of having the input parameter `elecPurchased`, it should read a list of `Hive.IO.EnergySystems` (i.e., all technologies that require or produce electricity: chiller, ashp, PV, CHP, ...)
- the component will need to identify how much electricity needs to be purchased from the grid, i.e., replacing the lines `var elecPurchased = new List<double>(); DA.GetDataList(1, elecPurchased);` with code contained in the two custom ghpython components as seen on the screenshot.
- you can locate those two custom ghpython components in the `EaCS3_E04_Hive_Template.gh` to the very right, just before the `Results` group

**Comment by ChrisZenhub** [comment]
possible relation with #707
