### ISSUE TITLE
Solar Irradiation | Joan's model

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#76]
(from WP_Components.xlsx)

Include Joan's Solar Irradiation model in hive.

**Comment by christophwaibel** [comment]
is this model enough?: https://github.com/architecture-building-systems/hive/tree/master/Core/solar

Also, Honeybee/Ladybug couples to Daysim / Radiance and can do almost everything needed. So, following our Cluster-idea, we could use many of existing LB/HB components, instead of re-inventing the fork.

re-open more specific issue, if needed
